### ISSUE TITLE
添加虚拟机快照失败

### ISSUE THREAD

**Issue by tasnrh** [welliamcao/VManagePlatform#10]
![image](https://cloud.githubusercontent.com/assets/26817652/26490903/da22aa7a-423f-11e7-9de3-c8092b80902b.png)
![image](https://cloud.githubusercontent.com/assets/26817652/26490906/dec5ade8-423f-11e7-9e56-42c0e2b0330f.png)

**Comment by welliamcao** [comment]
快照名称根虚拟机名称一样的吗？

**Comment by welliamcao** [comment]
拉去最新的代码，修复了这个bug
