### ISSUE TITLE
测试之后发现的问题总结

### ISSUE THREAD

**Issue by tasnrh** [welliamcao/VManagePlatform#11]
1、光驱不可连接
![image](https://cloud.githubusercontent.com/assets/26817652/26490991/432a921c-4240-11e7-95e8-2d8c658d1b6f.png)

2、内存和硬盘 统计信息不准
![image](https://cloud.githubusercontent.com/assets/26817652/26491027/69ea4d70-4240-11e7-939a-46ccec13b952.png)

3、虚拟化管理器需要先点击主机的管理网络才会出来，不是一直在首业显示
![image](https://cloud.githubusercontent.com/assets/26817652/26491097/bd6109da-4240-11e7-8b5e-0caf70f5918d.png)

4、

**Comment by welliamcao** [comment]
光驱XML格式里面定义的类型是什么样的？
