### ISSUE TITLE
添加主机后不能删除和添加网络失败

### ISSUE THREAD

**Issue by yeyingcai** [welliamcao/VManagePlatform#13]
添加了宿主机之后，找不到删除的选项，默认有一个default的网络，但是创建虚拟机的时候不能用，我想删除default网路后重新添加一个网络，但是添加失败。想删除宿主机后重新添加，没找到删除的选项。麻烦您协助一下。跪谢啊。

**Comment by welliamcao** [comment]
拉去一下最新代码，添加了删除主机入口。或者你直接在数据库里面删除也行，以下是删除语句，请根据自己情况修改where条件：
`
mysql> use vmanage;
mysql> delete from vmanageplatform_vmserver where server_ip="你要删除的宿主机IP";
 `
