### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by xiaosadexiaohai** [welliamcao/VManagePlatform#15]
![33](https://user-images.githubusercontent.com/18409309/27903078-9a41a866-626a-11e7-8b0d-8d2c6f97f0e7.png)
加不了
![image](https://user-images.githubusercontent.com/18409309/27903098-a53b3d0e-626a-11e7-8f2f-1cddced91325.png)

**Comment by xiaosadexiaohai** [comment]
而且节点还无法删除 @welliamcao

**Comment by welliamcao** [comment]
已经修复：[](https://github.com/welliamcao/VManagePlatform/commit/ff64efe4917c58babc19e860e9f97a36a6faa8eb)
