### ISSUE TITLE
ImportError: No module named VManagePlatform.settings

### ISSUE THREAD

**Issue by change41** [welliamcao/VManagePlatform#16]
![image](https://user-images.githubusercontent.com/29248210/27903984-ce8e3898-626d-11e7-9ea7-36789e9ae788.png)

**Comment by welliamcao** [comment]
执行python manage.py migrate时的路径正确吗？另外安装模块的时候要注意看一下模块是否全部安装正常。

**Comment by change41** [comment]
这个问题已经解决了，正确路径是
# cd /yourpath/VManagePlatform/
# python manage.py migrate
# python manage.py createsuperuser


路径正确后报Celery错误，升级Celery 到3.1也正常了，现在没有解决的是加载static目录下的样式文件报错404，晚点我下载最新的试试

**Comment by change41** [comment]
现成运行报错:
![image](https://user-images.githubusercontent.com/29248210/27943915-9c342f80-6315-11e7-8f56-6f54246f5607.png)
我的配置如下：
![image](https://user-images.githubusercontent.com/29248210/27943933-bbbfa33e-6315-11e7-97b4-4114a242ddc6.png)

**Comment by welliamcao** [comment]
1、/yourpath/VManagePlatform/ 安装文档已经更新了。
2、能否提供一下你的setting文件，STATICFILES_DIRS配置信息？
@change41

**Comment by change41** [comment]
![1](https://user-images.githubusercontent.com/29248210/27985053-319f9e46-6416-11e7-94e9-751a491351e9.png)
404的问题也解决了，是因为我开启了Debug
