### ISSUE TITLE
pip install -r requirements.txt(libvirt-python)报错解决

### ISSUE THREAD

**Issue by l-yb** [welliamcao/VManagePlatform#17]
VManagePlatform/requirements.txt (line 6))
Building wheels for collected packages: libvirt-python
/usr/bin/pkg-config --print-errors --atleast-version=0.9.11 libvirt
    Package libvirt was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libvirt.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libvirt' found
    error: command '/usr/bin/pkg-config' failed with exit status 1

-----------------------如题，安装libvirt-python时，需要提前yum 安装libvirt libvirt-devel
yum  install -y libvirt libvirt-devel

**Comment by welliamcao** [comment]
好的，下次我再更新readme文件。
