### ISSUE TITLE
requirements.txt问题多多

### ISSUE THREAD

**Issue by tasnrh** [welliamcao/VManagePlatform#5]
编译中断。

error: command 'gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/libvirt-python/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-7i6Mmm-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/libvirt-python
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.5', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/site-packages/pip-1.5.5-py2.7.egg/pip/__init__.py", line 185, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/site-packages/pip-1.5.5-py2.7.egg/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 30: ordinal not in range(128)

**Comment by welliamcao** [comment]
看上去是python的paramiko模块安装有问题：
# yum install zlib zlib-devel readline-devel bzip2-devel openssl-devel gdbm-devel libdbi-devel ncurses-libs kernel-devel libxslt-devel libffi-devel python-devel
yum安装所需依赖包之后再试一试

**Comment by tasnrh** [comment]
用这个命令requirements.txt文件过了，但是指数据库哪里出了问题：
[root@VManagePlatform VManagePlatform]# python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/lib64/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib64/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/lib64/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib64/python2.7/site-packages/django/contrib/auth/models.py", line 41, in <module>
    class Permission(models.Model):
  File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 139, in __new__
    new_class.add_to_class('_meta', Options(meta, **kwargs))
  File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 324, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/lib64/python2.7/site-packages/django/db/models/options.py", line 250, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/usr/lib64/python2.7/site-packages/django/db/__init__.py", line 36, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/usr/lib64/python2.7/site-packages/django/db/utils.py", line 241, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/usr/lib64/python2.7/site-packages/django/db/utils.py", line 112, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib64/python2.7/site-packages/django/db/backends/mysql/base.py", line 27, in <module>
    raise ImproperlyConfigured("Error loading MySQLdb module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module: No module named MySQLdb

**Comment by welliamcao** [comment]
用最新的requirements.txt安装

**Comment by tasnrh** [comment]
使用了最新的requirements.txt安装，一样的。
[root@VManagePlatform VManagePlatform]# pip install -r requirements.txt 
Requirement already satisfied: django==1.8.17 in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: Celery in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: django-celery in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: celery-with-redis in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: djangorestframework in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: paramiko in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: redis in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: libvirt-python in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied: supervisor in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 9))
Requirement already satisfied: MySQl-python in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 10))
Requirement already satisfied: DBUtils in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 11))
Requirement already satisfied: kombu<5.0,>=4.0.2 in /usr/lib/python2.7/site-packages (from Celery->-r requirements.txt (line 2))
Requirement already satisfied: pytz>dev in /usr/lib/python2.7/site-packages (from Celery->-r requirements.txt (line 2))
Requirement already satisfied: billiard<3.6.0,>=3.5.0.2 in /usr/lib64/python2.7/site-packages (from Celery->-r requirements.txt (line 2))
Requirement already satisfied: cryptography>=1.1 in /usr/lib64/python2.7/site-packages (from paramiko->-r requirements.txt (line 6))
Requirement already satisfied: pyasn1>=0.1.7 in /usr/lib/python2.7/site-packages (from paramiko->-r requirements.txt (line 6))
Requirement already satisfied: meld3>=0.6.5 in /usr/lib/python2.7/site-packages (from supervisor->-r requirements.txt (line 9))
Requirement already satisfied: amqp<3.0,>=2.1.4 in /usr/lib/python2.7/site-packages (from kombu<5.0,>=4.0.2->Celery->-r requirements.txt (line 2))
Requirement already satisfied: idna>=2.1 in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->-r requirements.txt (line 6))
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->-r requirements.txt (line 6))
Requirement already satisfied: packaging in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->-r requirements.txt (line 6))
Requirement already satisfied: six>=1.4.1 in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->-r requirements.txt (line 6))
Requirement already satisfied: setuptools>=11.3 in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->-r requirements.txt (line 6))
Requirement already satisfied: enum34 in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->-r requirements.txt (line 6))
Requirement already satisfied: ipaddress in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->-r requirements.txt (line 6))
Requirement already satisfied: cffi>=1.4.1 in /usr/lib64/python2.7/site-packages (from cryptography>=1.1->paramiko->-r requirements.txt (line 6))
Requirement already satisfied: vine>=1.1.3 in /usr/lib/python2.7/site-packages (from amqp<3.0,>=2.1.4->kombu<5.0,>=4.0.2->Celery->-r requirements.txt (line 2))
Requirement already satisfied: pyparsing in /usr/lib/python2.7/site-packages (from packaging->cryptography>=1.1->paramiko->-r requirements.txt (line 6))
Requirement already satisfied: pycparser in /usr/lib/python2.7/site-packages (from cffi>=1.4.1->cryptography>=1.1->paramiko->-r requirements.txt (line 6))

**Comment by tasnrh** [comment]
我的环境是CentOS 7,应该不会和操作系统有关系吧！

**Comment by welliamcao** [comment]
不会，你手动pip安装一下文件里面的模块，看看是哪个模块安装不上，再把这个安装不上的模块解决一下
