### ISSUE TITLE
部署完成后无法创建虚拟机，请问如何添加镜像和添加操作系统

### ISSUE THREAD

**Issue by tanshaofff** [welliamcao/VManagePlatform#8]
![qq 20170510184344](https://cloud.githubusercontent.com/assets/28594724/25895267/c8a407b6-35b1-11e7-9a69-51860b036d22.png)

**Comment by welliamcao** [comment]
把iso文件放在存储池里面，然后刷新存储池。

**Comment by tanshaofff** [comment]
请问有详细的部署文档吗- -新手好多不懂- -

**Comment by tanshaofff** [comment]
是用nfs的还是别的

**Comment by welliamcao** [comment]
都可以，你可以用nfs做一个ISO镜像共享，这样多个节点服务器挂载之后，再添加成存储池，可以统一使用与方便管理。
